<?php


use Zend\Form\FieldsetInterface;

$url_params = array(
	'controller' => 'items', 
	'action' => $action
);
if (isset($product_id) && (strcasecmp($action, 'edit') === 0)) {
	$url_params['id'] = $product_id;
}

$form->setAttribute('action', $this->url('invoices/default', $url_params))
     ->prepare();

echo $this->form()->openTag($form);

// NAME
$element = $form->get('name');
?>
<div class="control-group section-start<?php if($this->formElementErrors($element)) echo " error" ?>">
    <label class="control-label"><?php echo $element->getLabel() ?></label>
    <div class="controls">
        <?php echo $this->formElement($element);
        if($this->formElementErrors($element)) ?>
                    <span class="help-inline"><?php echo $this->formElementErrors($element) ?></span>
    </div>
</div>
<?php 
$element = $form->get('itemType');
?>
<div class="control-group <?php if($this->formElementErrors($element)) echo " error" ?>">
    <label class="control-label"><?php echo $element->getLabel() ?></label>
    <div class="controls">
        <?php echo $this->formElement($element);
        if($this->formElementErrors($element)) ?>
                    <span class="help-inline"><?php echo $this->formElementErrors($element) ?></span>
    </div>
</div>
<?php 
$element = $form->get('description');
?>
<div class="control-group <?php if($this->formElementErrors($element)) echo " error" ?>">
    <label class="control-label"><?php echo $element->getLabel() ?></label>
    <div class="controls">
        <?php echo $this->formElement($element);
        if($this->formElementErrors($element)) ?>
                    <span class="help-inline"><?php echo $this->formElementErrors($element) ?></span>
    </div>
</div>
<?php 
$element = $form->get('unitPrice');
?>
<div class="control-group <?php if($this->formElementErrors($element)) echo " error" ?>">
    <label class="control-label"><?php echo $element->getLabel() ?></label>
    <div class="controls">
        <?php echo $this->formElement($element);
        if($this->formElementErrors($element)) ?>
                    <span class="help-inline"><?php echo $this->formElementErrors($element) ?></span>
    </div>
</div>

<h3 class="section-header"><?php echo $this->translate("Taxes")?></h3>

<?php 
$taxes = $form->get('taxes');

// template
$elementOrFieldset = $taxes->getTemplateElement();
$element = $elementOrFieldset->get('id');

ob_start();
?>
<div class="control-group tax">
   	<label class="control-label"><?php echo $element->getLabel() ?></label>
   	<div class="controls">
       	<?php echo $this->formElement($element);
       	if($this->formElementErrors($element)) ?>
                   <span class="help-inline"><?php echo $this->formElementErrors($element) ?></span>
   	</div>
</div>
<?php 
$template = ob_get_contents();
ob_end_clean();

$template = $this->escapeHtmlAttr($template);
echo sprintf('<span id="template-add-another-tax" data-template="%s"></span>', $template);
?>


<div id="taxes-container">
<?php 
foreach ($taxes->getIterator() as $elementOrFieldset) :
		if ($elementOrFieldset instanceof FieldsetInterface) {
			foreach($elementOrFieldset as $element) :
?>
<div class="control-group tax <?php if($this->formElementErrors($element)) echo " error" ?>">
    <label class="control-label"><?php echo $element->getLabel() ?></label>
    <div class="controls">
        <?php echo $this->formElement($element);
        if($this->formElementErrors($element)) ?>
                    <span class="help-inline"><?php echo $this->formElementErrors($element) ?></span>
    </div>
</div>
<?php 
			endforeach;
		}
	
endforeach;
?>
</div>
<div class="control-group">
	<div class="controls">
		<a href="#" id="add_another_tax" class="link-new"><?php echo $this->translate("Add another tax")?></a>
	</div>
</div>
<script type="text/javascript">
<!--
	$('#add_another_tax').click(function(event) {
		event.preventDefault();

		currentCount = $('#taxes-container div.tax').length;
		//element = $('#template-add-another-tax').clone().html();
		element = $('#template-add-another-tax').data('template');
		element = element.replace(/__index__/g, currentCount);
		element = $.parseHTML(element);
		
		$('#taxes-container').append(element);
		return false;
	});
//-->
</script>
<?php
// CSRF 
echo $this->formHidden($form->get('csrf'));
?>
<div class="submit-container">
	<span class="button large inline green">
		<?php echo $this->formElement($form->get('submit')); ?>
	</span>
</div>
<?php 
echo $this->form()->closeTag();
     