<h2 class="pt"><?php echo $this->translate("Edit Item");?></h2>
<div class="clearb"></div>
<?php
$form->setAttribute('action', $this->url('invoices/default', array('controller' => 'items', 'action' => 'edit', 'id' => $item->getId())))
     ->prepare();

echo $this->form()->openTag($form);

$product = $form->get('product');
$is_start = true;
foreach ($product as $element) : ?>
<div class="control-group<?php if($is_start) echo " section-start" ?><?php if($this->formElementErrors($element)) echo " error" ?>">
    <label class="control-label"><?php echo $element->getLabel() ?></label>
    <div class="controls">
        <?php echo $this->formElement($element);
        if($this->formElementErrors($element)) ?>
                    <span class="help-inline"><?php echo $this->formElementErrors($element) ?></span>
    </div>
</div>
<?php 
	$is_start = false;
endforeach;
 
echo $this->formHidden($form->get('csrf'));
?>
<div class="submit-container">
	<span class="button large inline green">
		<?php echo $this->formElement($form->get('submit')); ?>
	</span>
</div>
<?php 
echo $this->form()->closeTag();
?>

<script type="text/javascript">
	if ($('select[name="product[itemType]"]').val() == 'service') {
		$('input[name="product[unitCost]"]').closest('.control-group').hide();
	}
	
    $('select[name="product[itemType]"]').change(function(){
        if ($(this).val() == 'service') {
            $('input[name="product[unitCost]"]').closest('.control-group').hide();
        } else {
        	$('input[name="product[unitCost]"]').closest('.control-group').show();
        }
    });
</script>
