<h2><?php echo $this->translate("New Item");?></h2>

<?php
$form->setAttribute('action', $this->url('invoices/default', array('controller' => 'items', 'action' => 'edit', 'id' => $item->getId())))
     ->prepare();

echo $this->form()->openTag($form);

$product = $form->get('product');

echo $this->formRow($product->get('name'));
echo $this->formRow($product->get('description'));
echo $this->formRow($product->get('unitPrice'));
echo $this->formRow($product->get('unitCost'));
echo $this->formRow($product->get('taxId'));

echo $this->formHidden($form->get('csrf'));
echo $this->formElement($form->get('submit'));

echo $this->form()->closeTag();