<h2 class="pt"><?php echo $this->translate("Items"); ?></h2>
<a href="<?php echo $this->url('invoices/default', array('controller' => 'items', 'action' => 'add'));?>" class="button large green create right  " style="">
	<span><?php echo $this->translate("New Item"); ?></span>
</a>
<div class="clearb"></div>

<table class="table">
<tr>
    <th><?php echo $this->translate("Name")?></th>
    <th><?php echo $this->translate("Type")?></th>
    <th><?php echo $this->translate("Price")?></th>
    <th>&nbsp;</th>
</tr>
<?php 
	foreach ($products as $product) : 
?>
<tr>
    <td>
    	<?php echo $this->escapeHtml($product->getName()); ?>
    </td>
    <td>
    	<?php 
    		if ($product->isProduct()) {
    			echo $this->translate("Product");
    		} elseif ($product->isService()) {
    			echo $this->translate("Service");
    		} else {
    			// Custom type
    			echo ucfirst($this->getItemType());
    		}
    	?>
    </td>
    <td>
    	<?php echo sprintf('%0.2f', round($product->getUnitPrice(),2)); ?>
    </td>
    <td>
    	<a href="<?php echo $this->url('invoices/default', array('controller' => 'items', 'action' => 'edit', 'id' => $product->getId()));?>"><?php echo $this->translate("Edit")?></a>
    </td>
</tr>
<?php
	endforeach; 
?>
</table>