<?php
$url_params = array(
	'controller' => 'clients', 
	'action' => $action
);
if (isset($customer_id) && (strcasecmp($action, 'edit') === 0)) {
	$url_params['id'] = $customer_id;
}

$form->setAttribute('action', $this->url('people/default', $url_params))
     ->prepare();

echo $this->form()->openTag($form);

// NAME
$element = $form->get('name');
?>
<div class="control-group section-start<?php if($this->formElementErrors($element)) echo " error" ?>">
    <label class="control-label"><?php echo $element->getLabel() ?></label>
    <div class="controls">
        <?php echo $this->formElement($element);
        if($this->formElementErrors($element)) ?>
                    <span class="help-inline"><?php echo $this->formElementErrors($element) ?></span>
    </div>
</div>
<?php 
$element = $form->get('taxId');
?>
<div class="control-group <?php if($this->formElementErrors($element)) echo " error" ?>">
    <label class="control-label"><?php echo $element->getLabel() ?></label>
    <div class="controls">
        <?php echo $this->formElement($element);
        if($this->formElementErrors($element)) ?>
                    <span class="help-inline"><?php echo $this->formElementErrors($element) ?></span>
    </div>
</div>

<?php 
$element = $form->get('country');
?>
<div class="control-group <?php if($this->formElementErrors($element)) echo " error" ?>">
    <label class="control-label"><?php echo $element->getLabel() ?></label>
    <div class="controls">
        <?php echo $this->formElement($element);
        if($this->formElementErrors($element)) ?>
                    <span class="help-inline"><?php echo $this->formElementErrors($element) ?></span>
    </div>
</div>

<div class="control-group">
		<label class="control-label"><?php echo $form->get('street')->getLabel() ?></label>
		<div class="controls">
			<div class="append-bottom-1">
				<?php echo $this->formElement($form->get('street'))?>
				<div class="example"><?php echo $this->translate("Street 1")?></div>
			</div>

			<div class="append-bottom-1">
				<?php echo $this->formElement($form->get('street2'))?>
				<div class="example"><?php echo $this->translate("Street 2")?></div>
			</div>

			<div class="span-7">
				<?php echo $this->formElement($form->get('locality'))?>
				<div class="example"><?php echo $this->translate("City")?></div>
			</div>

			<div class="span-10">
				<?php echo $this->formElement($form->get('region'))?>
				<div class="example"><?php echo $this->translate("Province/State")?></div>
			</div>

			<div class="span-7">
				<?php echo $this->formElement($form->get('zip'))?>
				<div class="example"><?php echo $this->translate("Postal/Zip Code")?></div>
			</div>
		</div>
	</div>
<?php
// phone
$element = $form->get('phone');
?>
<div class="control-group<?php if($this->formElementErrors($element)) echo " error" ?>">
    <label class="control-label"><?php echo $element->getLabel() ?></label>
    <div class="controls">
        <?php echo $this->formElement($element);
        if($this->formElementErrors($element)) ?>
                    <span class="help-inline"><?php echo $this->formElementErrors($element) ?></span>
    </div>
</div>
<?php
// FAX
$element = $form->get('fax');
?>
<div class="control-group<?php if($this->formElementErrors($element)) echo " error" ?>">
    <label class="control-label"><?php echo $element->getLabel() ?></label>
    <div class="controls">
        <?php echo $this->formElement($element);
        if($this->formElementErrors($element)) ?>
                    <span class="help-inline"><?php echo $this->formElementErrors($element) ?></span>
    </div>
</div>

<h3 class="section-header"><?php echo $this->translate("Contacts")?></h3>
<?php 
$contacts = $form->get('contacts');

// template
$elementOrFieldset = $contacts->getTemplateElement();

ob_start();
?>
<div class="contact">
	<div class="span-20">
		<div class="control-group required">
			<label class="control-label"><?php echo $elementOrFieldset->get('email')->getLabel(); ?></label>
			<div class="controls">
				<?php echo $this->formElement($elementOrFieldset->get('email')); ?>
			</div>
		</div>
	
		<div class="control-group">
			<label class="control-label"><?php echo $this->translate("Contact Name")?></label>
			<div class="controls">
				<div class="span-5 append-half">
					<?php echo $this->formElement($elementOrFieldset->get('firstName')); ?>
					<div class="example"><?php echo $elementOrFieldset->get('firstName')->getLabel(); ?></div>
				</div>
				<div class="span-5">
					<?php echo $this->formElement($elementOrFieldset->get('lastName')); ?>
					<div class="example"><?php echo $elementOrFieldset->get('lastName')->getLabel(); ?></div>
				</div>
			</div>
		</div>
	</div>
	
	<div class="span-18 label-column-small">
		<div class="control-group">
			<label class="control-label"><?php echo $elementOrFieldset->get('phone')->getLabel() ?></label>
			<div class="controls">
				<?php echo $this->formElement($elementOrFieldset->get('phone')); ?>
			</div>
		</div>
	
		<div class="control-group">
			<label class="control-label"><?php echo $elementOrFieldset->get('mobilePhone')->getLabel() ?></label>
			<div class="controls">
				<?php echo $this->formElement($elementOrFieldset->get('mobilePhone')); ?>
			</div>
		</div>
	</div>
	<div class="clearb"></div>
</div>
<?php 
$template = ob_get_contents();
ob_end_clean();

$template = $this->escapeHtmlAttr($template);
echo sprintf('<span id="template-add-another-contact" data-template="%s"></span>', $template);
?>


<div id="contacts-container">
<?php 
foreach ($contacts->getIterator() as $elementOrFieldset) :
		//if ($elementOrFieldset instanceof FieldsetInterface) {
		//	foreach($elementOrFieldset as $element) :
?>
<div class="contact">
	<div class="span-20">
		<div class="control-group required">
			<label class="control-label"><?php echo $elementOrFieldset->get('email')->getLabel(); ?></label>
			<div class="controls">
				<?php echo $this->formElement($elementOrFieldset->get('email')); ?>
			</div>
		</div>
	
		<div class="control-group">
			<label class="control-label"><?php echo $this->translate("Contact Name")?></label>
			<div class="controls">
				<div class="span-5 append-half">
					<?php echo $this->formElement($elementOrFieldset->get('firstName')); ?>
					<div class="example"><?php echo $elementOrFieldset->get('firstName')->getLabel(); ?></div>
				</div>
				<div class="span-5">
					<?php echo $this->formElement($elementOrFieldset->get('lastName')); ?>
					<div class="example"><?php echo $elementOrFieldset->get('lastName')->getLabel(); ?></div>
				</div>
			</div>
		</div>
	</div>
	<div class="span-18 label-column-small">
		<div class="control-group">
			<label class="control-label"><?php echo $elementOrFieldset->get('phone')->getLabel() ?></label>
			<div class="controls">
				<?php echo $this->formElement($elementOrFieldset->get('phone')); ?>
			</div>
		</div>
	
		<div class="control-group">
			<label class="control-label"><?php echo $elementOrFieldset->get('mobilePhone')->getLabel() ?></label>
			<div class="controls">
				<?php echo $this->formElement($elementOrFieldset->get('mobilePhone')); ?>
			</div>
		</div>
	</div>
	<div class="clearb"></div>
</div>
<?php 
		//	endforeach;
		//}
	
endforeach;
?>
</div>
<div class="control-group">
	<div class="controls">
		<a href="#" id="add_another_contact" class="link-new"><?php echo $this->translate("Add another contact")?></a>
	</div>
</div>
<script type="text/javascript">
<!--
	$('#add_another_contact').click(function(event) {
		event.preventDefault();

		currentCount = $('#contacts-container div.contact').length;
		//element = $('#template-add-another-tax').clone().html();
		element = $('#template-add-another-contact').data('template');
		element = element.replace(/__index__/g, currentCount);
		element = $.parseHTML(element);
		
		$('#contacts-container').append(element);
		return false;
	});
//-->
</script>


<h3 class="section-header"><?php echo $this->translate("Internal Information")?></h3>
<?php
$element = $form->get('notes');
?>
<div class="control-group<?php if($this->formElementErrors($element)) echo " error" ?>">
    <label class="control-label"><?php echo $element->getLabel() ?></label>
    <div class="controls">
        <?php echo $this->formElement($element);
        if($this->formElementErrors($element)) ?>
                    <span class="help-inline"><?php echo $this->formElementErrors($element) ?></span>
    </div>
</div>
<?php
// CSRF 
echo $this->formHidden($form->get('csrf'));
?>
<div class="submit-container">
	<span class="button large inline green">
		<?php echo $this->formElement($form->get('submit')); ?>
	</span>
</div>
<?php 
echo $this->form()->closeTag();
     