<div id="wizard-navigation">
	<?php echo $this->navigation('settings_navigation')->menu(); ?>
</div>
             
<?php
$form->setAttribute('action', $this->url('settings/default', array('action' => 'company')))
     ->prepare();

echo $this->form()->openTag($form);
?>

<div class="form-header">
	<h2><?php echo $this->translate("Company Profile"); ?></h2>
	<?php echo $this->translate("This information is used for invoicing, emails, and more. Make sure it's correct!")?>
</div>
<?php 
echo $this->formHorizontalRow($form->get('name'));
echo $this->formHorizontalRow($form->get('taxId'));
echo $this->formHorizontalRow($form->get('currency'));
echo $this->formHorizontalRow($form->get('country'));
?>

<div class="control-group">
		<label class="control-label"><?php echo $form->get('street')->getLabel() ?></label>
		<div class="controls">
			<div class="append-bottom-1">
				<?php echo $this->formElement($form->get('street'))?>
				<div class="example"><?php echo $this->translate("Street 1")?></div>
			</div>

			<div class="append-bottom-1">
				<?php echo $this->formElement($form->get('street2'))?>
				<div class="example"><?php echo $this->translate("Street 2")?></div>
			</div>

			<div class="span-7">
				<?php echo $this->formElement($form->get('locality'))?>
				<div class="example"><?php echo $this->translate("City")?></div>
			</div>

			<div class="span-10">
				<?php echo $this->formElement($form->get('region'))?>
				<div class="example"><?php echo $this->translate("Province/State")?></div>
			</div>

			<div class="span-7">
				<?php echo $this->formElement($form->get('zip'))?>
				<div class="example"><?php echo $this->translate("Postal/Zip Code")?></div>
			</div>
		</div>
	</div>
<?php
echo $this->formHorizontalRow($form->get('email'));
echo $this->formHorizontalRow($form->get('phone'));
echo $this->formHorizontalRow($form->get('fax'));


?>


<?php
// CSRF 
echo $this->formHidden($form->get('csrf'));
?>
<div class="submit-container">
	<span class="button large inline green">
		<?php echo $this->formElement($form->get('submit')); ?>
	</span>
</div>
<?php 
echo $this->form()->closeTag();
     