<div id="wizard-navigation">
	<?php echo $this->navigation('settings_navigation')->menu(); ?>
</div>

<div class="form-header">
	<h2><?php echo $this->translate("Taxes"); ?></h2>
	<?php echo $this->translate("Need to charge your clients tax? Customize your taxes here and reuse them on your future invoices and expenses."); ?>
</div>

<?php 
$form->setAttribute('action', $this->url('settings/default', array('action' => 'taxes')))
     ->prepare();

echo $this->form()->openTag($form);
?>
<table class="table">
<tr>
    <th><?php echo $this->translate("Description")?></th>
    <th><?php echo $this->translate("Rate")?></th>
    <th><?php echo $this->translate("Equalization")?></th>
    <th><?php echo $this->translate("Active")?></th>
</tr>
<?php
$taxes = $form->get('taxes'); 
foreach ($taxes->getIterator() as $elementOrFieldset) : 
?>
<tr>
    <td>
    	<?php echo $this->formElement($elementOrFieldset->get("id")); ?>
    	<?php echo $this->formElement($elementOrFieldset->get("description")); ?>
    </td>
    <td><?php echo $this->formElement($elementOrFieldset->get("percentage")); ?> %</td>
    <td><?php echo $this->formElement($elementOrFieldset->get("equalization")); ?> %</td>
    <td><?php echo $this->formElement($elementOrFieldset->get("active")); ?></td>
</tr>
<?php endforeach; ?>
</table>
<?php
// CSRF 
echo $this->formHidden($form->get('csrf'));
?>
<div class="submit-container">
	<span class="button large inline green">
		<?php echo $this->formElement($form->get('submit')); ?>
	</span>
</div>
<?php 
echo $this->form()->closeTag(); ?>