<div id="wizard-navigation">
	<?php echo $this->navigation('settings_navigation')->menu(); ?>
</div>

<div class="form-header">
	<h2><?php echo $this->translate("Taxes"); ?></h2>
	<?php echo $this->translate("Need to charge your clients tax? Customize your taxes here and reuse them on your future invoices and expenses."); ?>
</div>

<table class="table">
<tr>
    <th><?php echo $this->translate("Description")?></th>
    <th><?php echo $this->translate("Rate")?></th>
    <?php if ($tax_equalization) : ?>
    <th><?php echo $this->translate("Equalization")?></th>
    <?php endif; ?>
    <th><?php echo $this->translate("Active")?></th>
</tr>
<?php 
	$array_index = 0;
	foreach ($taxes as $tax) : 
?>
<tr>
    <td>
    	<input name="taxes[<?php echo $array_index; ?>][id]" type="hidden" value="<?php echo $this->escapeHtml($tax->getId());?>" />
    	<input class="formTextMed" maxlength="15" name="taxes[<?php echo $array_index; ?>][description]" type="text" value="<?php echo $this->escapeHtml($tax->getDescription());?>" style="width: 200px">
    </td>
    <td>
    	<input class="formTextMini" onkeypress="return numbersonly(this,event)" maxlength="7" name="taxes[<?php echo $array_index; ?>][percentage]" type="text" value="<?php echo $this->escapeHtml($tax->getPercentage());?>" style="width:50px;"> %
    </td>
    <?php if ($tax_equalization) : ?>
    <td>
    	<input class="formTextMini" onkeypress="return numbersonly(this,event)" maxlength="7" name="taxes[<?php echo $array_index; ?>][equalization]" type="text" value="<?php echo $this->escapeHtml($tax->getEqualization());?>" style="width:50px;"> %
    </td>
    <?php endif; ?>
    <td>
    	<input type="checkbox" name="taxes[<?php echo $array_index; ?>][active]" <?php echo ($tax->getActive()) ? 'checked="checked"' : ''; ?>" />
    </td>
</tr>
<?php
		$array_index++; 
	endforeach; 
?>
</table>